---
title: "Penguins EDA"
format:
  html:
    code-fold: true
---

## Penguin Size and Mass by Sex and Species

``` {.r .cell-code}
library(palmerpenguins)
library(dplyr)
library(ggplot2)

df <- palmerpenguins::penguins
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(palmerpenguins)
library(dplyr)
library(ggplot2)

df <- palmerpenguins::penguins

```

``` {.r .cell-code}
df %>%
  group_by(species, sex) %>%
  summarise(
    across(
      where(is.numeric), 
      \(x) mean(x, na.rm = TRUE)
      )
    ) %>%
  knitr::kable()
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df %>%
  group_by(species, sex) %>%
  summarise(
    across(
      where(is.numeric), 
      \(x) mean(x, na.rm = TRUE)
      )
    ) %>%
  knitr::kable()
```

## Penguin Size vs Mass by Species

``` {.r .cell-code}
df %>%
  ggplot(aes(x = bill_length_mm, y = body_mass_g, color = species)) +
  geom_point() + 
  geom_smooth(method = "lm")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
df %>%
  ggplot(aes(x = bill_length_mm, y = body_mass_g, color = species)) +
  geom_point() + 
  geom_smooth(method = "lm")
```

```{r}
#install.packages("DBI")
```

```{r}
#con <- DBI::dbConnect(
#  duckdb::duckdb(), 
#  dbdir = "my-db.duckdb"
#  )
#df <- dplyr::tbl(con, "penguins")
```

```{r}
#DBI::dbDisconnect(con, shutdown = TRUE )

```
